### ISSUE TITLE
Current state of DevTools?

### ISSUE THREAD

**Issue by timbur** [js-next/react-style#108]
I see there's an issue from November that briefly mentioned the possibly of extending react-devtools to improve workflow with react-style.  For most people, react-hot-loader is probably sufficient, but I personally prefer a tighter feedback loop, plus the native CSS editing tools are pretty sweet these days.

It could just be that I haven't yet dived deep enough into react-style (or read through enough issues), but I'm not seeing anything that would suggest changes made via native CSS tools get reflected automatically within the `Stylesheet.create` declaration.  Is it because it's a bad idea?  Not worth the effort?  Or perhaps someone just needs to do it?

**Comment by SanderSpies** [comment]
It's a good idea, but takes some effort to get started - my focus regarding React Style for now is to make sure the basics are good. I'd like to start on a dev tools implementation - lots of fun stuff can be explored, but for now it's not on my agenda.

**Comment by timbur** [comment]
Thanks for the quick reply.

I'm putting together a development toolkit for ES6+React, which includes some extensions.  So this week or the next, I will probably start on an extension that plays nice with both react-style and the inspector's CSS tools.

Off the top of your head, what fun stuff did you have in mind to explore?  

Also, I haven't yet really put much time into learning the ins and outs of react-style, and I'm pretty lazy, so I have a couple of quick questions about it that you could probably answer quicker than I could figure out for myself.  When generating CSS (at least with the webpack plugin), I saw the use of adjoined class selectors (e.g., `.foo.foo1.etc`), but I'm curious as to what is generated for child selectors, if anything.  I agree with the consensus that child selectors are bad, but in some cases I think it would be way overkill to factor some child element into its own React class just to style it.  So in my own projects, I use verbose selectors *instead* of child selectors.

So for (a very contrived) example, suppose the markup looks something like this:
```js
<Foo>
  <ul>
    <li style={{color: someColor}}>bar</li>
  </ul>
</Foo>
```

The generated CSS might look something like this (or more descriptive if necessary) where the respective `li` elements are of course given a matching class name:
```css
.Foo__ul__li {
  color: #ff0000;
}
```

Does react-style do anything like this?  If not, what are your thoughts on it?

And my other question is:  Does react-style take full advantage of CSS?  By that I mean, how much CSS functionality has been rewritten in JS?  I agree that the style should be completely dependent on state and inline styles make certain things easier, but it also makes sense to me that we should make use of any CSS features where possible and then fallback to inline styles for any nontrivial styling.

My apologies if these questions have already been answered elsewhere.  :)

**Comment by SanderSpies** [comment]
We don't do child selectors, and so far I haven't seen the need for them. Actually I think they should be avoided due to being a maintenance hazard. Also your example seems to be a bit flawed as we need to generate CSS at build time and it's very hard to tell what's going to be rendered on the page at that moment. So that's why we define styles at the module level to be able to extract them at build time. 

Unfortunately we seem to have some regression with our generated classNames - we should definitely add a fileName prefix again :+1: 

We aim to support both inline styles and CSS stylesheets. So that limits our options a bit, but I think it's for the better. We try go for the best effort for each functionality - it takes some extra time, but I believe it's for the better. I think adding pseudo classes and auto prefixing will make React Style ready for 1.0 release. I'm already exploring stuff beyond that with react-magician (animations) and react-style-layout (ported Polymer's layout system to React Style).

**Comment by timbur** [comment]
I gave a bad (misleading) example.  That was meant to represent the markup, not the JSX, so I shouldn't have included the JSX but wanted to convey the dynamic possibility.

I should have included something like this, as it's more what I had in mind (very debatable syntax but you get the idea):
```js
var styles = StyleSheet.create({
    Foo: {
      color: 'red',
      backgroundColor: 'white',
      '> ul > li': {
        color: someColor
      },
      ':hover': {
        '> ul > li': {
          color: someOtherColor
        }
      }
    }
});
```

You could of course just give each `li` their own style (`.Foo__item` or whatever) but in some cases it seems like overkill, especially if something like the `:hover > ul > li` could be automated in that you don't have to manually attach the style attribute to the `li` elements; the renderer would know that it should be done.  And it could use existing CSS functionality - e.g., it might result in a CSS selector like `.Foo:hover .Foo__ul__li { /* etc. */ }`.  Beyond that, all of this is easily decipherable within browsers' tools (Sources panel, CSS editing, etc.) and should be easy enough to be reflect changes upon the style module (code) itself.

**Comment by timbur** [comment]
Better yet, rather than explicitly using `>`, it might make more sense to be able to define relationships between styles.  This would avoid any extensions of the renderer and eliminate any maintenance hazards.  Or does `react-style` already have something like this planned?

```js
var styles = StyleSheet.create({
    Foo: {
      color: 'red',
      backgroundColor: 'white',
      ':hover': {
        Foo__item: {
          color: someOtherColor
        }
      }
    },
    Foo__item: {
      color: someColor
    }
});
```

```jsx
<Foo styles={[styles.Foo, dynamicStyles]}>
  <ul>
    <li styles={{[styles.Foo__item]}}>bar</li>
  </ul>
</Foo>
```

```css
.Foo {
    color: red;
    background-color: white;
}
.Foo__item {
    color: blue;
}
.Foo:hover .Foo__item {
    color: green;
}
```
