### ISSUE TITLE
Media queries not working when resizing browser

### ISSUE THREAD

**Issue by triplehenry** [js-next/react-style#109]
Is there a way to get media queries to work when resizing the browser?  It only works for me when I refresh the page.

**Comment by SanderSpies** [comment]
They should always work, if not it's a bug - do you have a repo for me with the issue?

**Comment by triplehenry** [comment]
Sorry I don't have a repo for this but here is the code for it.

```javascript
mediaQueries = {
    webOnly: "@media screen and (min-width: 992px)",
    tabletOnly: "@media screen and (min-width: 768px) and (max-width: 991px)",
    mobileOnly: "@media screen and (max-width:767px)",
    mobileAndTablet: "@media screen and (max-width:991px)"
};
```

```javascript
import React from 'react';
import StyleSheet from 'react-style';

const FeedPage = React.createClass({
    render() {
        return (
            <div className="ui four column stackable page grid" style={style.wrapper}>
                ...
            </div>
        );
    }
});

let css = {
    wrapper: {
        width: "1000px",
        padding: "0",
        margin: "0 auto 80px"
    }
};

css[mediaQueries.mobileAndTablet] = {
    wrapper: {
        width: "100%",
        margin: "0 auto",
        textAlign: "center",
        paddingTop: "40px"
    }
};

let style = StyleSheet.create(css);
```

For the code above, when I resize the browser, the "wrapper" element does not have the media queries style applied to it.

**Comment by SanderSpies** [comment]
I guess you are using babel and react-style-webpack-plugin ?

**Comment by triplehenry** [comment]
I'm using babel but not react-style-webpack-plugin.

**Comment by SanderSpies** [comment]
@triplehenry I see you are using `style=` instead of React Style's `styles=`. Could you try to use `styles=` and tell me what the result is?

**Comment by triplehenry** [comment]
@SanderSpies No difference when I switched to `styles=`.

**Comment by SanderSpies** [comment]
You need to load React Style before React, that should solve everything :+1: 

We need this to be able to patch React functions, before they become "private".

**Comment by triplehenry** [comment]
Thanks.

**Comment by maxshutyak** [comment]
Load React Style before React doesn't help me

**Comment by maxshutyak** [comment]
Please help me to fix it. Css Media queries only works when i reload page but not when i am resizing browser window
