### ISSUE TITLE
How to use ReactStyle ?

### ISSUE THREAD

**Issue by jide** [js-next/react-style#111]
In the article at https://andreypopp.com/posts/2014-08-06-react-style.html, the ReactStyle wrapper is mentioned, but it is not mentioned in the docs. Moreover the configuration of webpack is different in the blog post and in the examples folder.

How is it supposed to work ? Is it a webpack loader supposed to preprocess the js file ? If so, what's the correct configuration ?

Thanks for your help.

**Comment by jide** [comment]
That article confused me a lot, it was unclear the API changed... @andreypopp Would be great if you added some words at the top of the article ;)

Here's a copy from a chat on slack's Reactiflux : 

Hey chan ! I'm having hard time to understand the whole react-style thing, I see "ReactStyle()" in some places, and "StyleSheet.create()" in others... I guess it's the old API vs the new one ?

lenny [1:13 AM] 
@jide: yes, it now uses the latter, to be the same as with React Native

jide [1:16 AM] 
Ok thank you ! What I don't get is that the old API seemed more dynamic, e.g. allowing to use props in values, I only see static stylesheets  with the new one now... I'm missing something ?

lenny [1:20 AM] 
you can still override the styles with other values, since the `styles` prop accepts an array

lenny [1:20 AM]
and those could come from props

jide [1:23 AM] 
Ok, confirms my intuition then. That old blog article confused me soooo much ! Thanks for the help

**Comment by SanderSpies** [comment]
@jide I would recommend to take a look at the examples here: https://github.com/js-next/react-style/tree/master/examples/0.13
