### ISSUE TITLE
LineHeight not in Pixels 

### ISSUE THREAD

**Issue by mosch** [js-next/react-style#120]
I'm using this module to share CSS between react-native an an webapp.

When using the line-height property, this library doesn't add the "px" suffix. It's ok to use unitless values in CSS for the line-height. The problem is that all values are unitless in react-native. And by defining it in react-native it get translated to "pixels".

If my usecase is important for this, you might consider to add the px suffix to this value. 

_I also think having a unitless line-height in css is very uncommon_

**Comment by rwoody** [comment]
I regularly experience this issue with regular React. The behavior is not the same with regard to other style props and this wastes development time.

**Comment by alfrednerstu** [comment]
It's great to use line-height unit-less in CSS, then it just works as a multiplier of the font-size

**Comment by mosch** [comment]
@alfrednerstu jipp, your right - still pretty uncommon.

**Comment by af7** [comment]
+1 It should be consistent with the other props, if possible.

**Comment by herodrigues** [comment]
Got the same result in one of my apps.
By the way, I had to use single quotes.

**Comment by tennisgent** [comment]
Just ran into this again. Really painful.

**Comment by khiav223577** [comment]
+1. Still a Problem in 2017.

**Comment by herodrigues** [comment]
Use pixels instead of a single number. For example, `lineHeight: '20px'`

**Comment by mosch** [comment]
Closing this since unmaintained.
