### ISSUE TITLE
Changing Style Doesn't Live Update Webpack

### ISSUE THREAD

**Issue by ronag** [js-next/react-style#37]
I am using React + React Style with Web Pack + react-hot-loader.

Everything seems to work fine. However, when changing the code inside a "ReactStyle" the css is not updated. Instead, after changing the code inside a "ReactStyle" I need to do some kind of "dummy" change to the React components (e.g. add a "dummy" function) which causes the component to update and the css to update.

**Comment by SanderSpies** [comment]
Too old, if this is still an issue - please reopen.
