### ISSUE TITLE
@font-face?

### ISSUE THREAD

**Issue by ronag** [js-next/react-style#56]
If I want to use a .ttf font it seems I must first declare a @font-face. How would I do that with react-style?

**Comment by SanderSpies** [comment]
Closing this one, agreeing with @andreypopp here.

**Comment by zealoushacker** [comment]
What about the use case of wanting to load a *@font-face* on demand? Wouldn't want to use `css-loader` in that case, now would we?

**Comment by wonderdogone** [comment]
What about in a case where you are rendering html on the server with inline styles?
