### ISSUE TITLE
Mass output of selectors

### ISSUE THREAD

**Issue by natew** [js-next/react-style#61]
Even for single element usage, I get selectors like this:

    .c8ed992bf__5_10_, .c8ed992bf__5_10_.c8ed992bf__5_10_1, .c8ed992bf__5_10_.c8ed992bf__5_10_1.c8ed992bf__5_10_2, .c8ed992bf__5_10_.c8ed992bf__5_10_1.c8ed992bf__5_10_2.c8ed992bf__5_10_3, .c8ed992bf__5_10_.c8ed992bf__5_10_1.c8ed992bf__5_10_2.c8ed992bf__5_10_3.c8ed992bf__5_10_4, .c8ed992bf__5_10_.c8ed992bf__5_10_1.c8ed992bf__5_10_2.c8ed992bf__5_10_3.c8ed992bf__5_10_4.c8ed992bf__5_10_5, .c8ed992bf__5_10_.c8ed992bf__5_10_1.c8ed992bf__5_10_2.c8ed992bf__5_10_3.c8ed992bf__5_10_4.c8ed992bf__5_10_5.c8ed992bf__5_10_6, .c8ed992bf__5_10_.c8ed992bf__5_10_1.c8ed992bf__5_10_2.c8ed992bf__5_10_3.c8ed992bf__5_10_4.c8ed992bf__5_10_5.c8ed992bf__5_10_6.c8ed992bf__5_10_7, .c8ed992bf__5_10_.c8ed992bf__5_10_1.c8ed992bf__5_10_2.c8ed992bf__5_10_3.c8ed992bf__5_10_4.c8ed992bf__5_10_5.c8ed992bf__5_10_6.c8ed992bf__5_10_7.c8ed992bf__5_10_8, .c8ed992bf__5_10_.c8ed992bf__5_10_1.c8ed992bf__5_10_2.c8ed992bf__5_10_3.c8ed992bf__5_10_4.c8ed992bf__5_10_5.c8ed992bf__5_10_6.c8ed992bf__5_10_7.c8ed992bf__5_10_8.c8ed992bf__5_10_9

I see in the source a generator function for this, just wondering what the purpose is?

**Comment by SanderSpies** [comment]
We now support configuring the CSS output, but have a default of 10. (see readme for details)
