### ISSUE TITLE
react-style & ReactCSSTransitionGroup

### ISSUE THREAD

**Issue by Yox2l** [js-next/react-style#85]
Hi react-style team,

Is there a way to define the css part of ReactCSSTransitionGroup in JS using react-style?
http://facebook.github.io/react/docs/animation.html

Thanks,
Yox2l

**Comment by SanderSpies** [comment]
@nelix @Yox2l Apologies for the (very) late reply (mostly due to positive personal matters). 

A very simple solution would be to create styles like:
```
fooStyle: ReactStyle({
  backgroundColor: 'orange'
}, 'example-leave');
```

**Comment by Yox2l** [comment]
@SanderSpies that make sense, Thank!
