### ISSUE TITLE
One element seems to not be picking up one of the styles

### ISSUE THREAD

**Issue by natew** [js-next/react-style#87]
So unfortunately I don't think I can extract this anytime soon, but before I go digging too far would you have any idea why this wouldn't be working.  I'm using the inline-styles branch.

Here's a screenshot that illustrates the problem well:

![](https://s3.amazonaws.com/f.cl.ly/items/1c132Q221D3m1n3s2n2k/Image%202014-12-12%20at%206.56.08%20PM.png)

I have two styles in an array, the first has `pointEvents: 'none'`, and the second has a few others. For some reason, and this is the only case I can see happening of this, the first style isn't being applied. Notice, no `pointer-events` on the element highlighted.

**Comment by SanderSpies** [comment]
Apologies for the late reply, will be looking into the inline-styles branch today. The branch shouldn't be used for now as it simply doesn't work properly yet.

**Comment by SanderSpies** [comment]
So the branch has been updated and this should work now. If there are any issues let me know.

**Comment by SanderSpies** [comment]
@natew is this still an issue?

**Comment by natew** [comment]
Sorry, I'll close. Not sure why this was happening but far enough that I can't reproduce.
