### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by ronag** [js-next/react-style#88]
What is the status of this project? Have been quiet for a while now. Is it still actively maintained and developed?

**Comment by SanderSpies** [comment]
Kinda busy with (very positive) personal matters at the moment. I'll try to
invest some time this week.

**Comment by SanderSpies** [comment]
Also, at React conf I'll be discussing CSS in JS with @Vjeux. I want to
make sure that React Style is going into the right direction :-).

**Comment by ronag** [comment]
Happy to hear that!

**Comment by robertknight** [comment]
@SanderSpies Please write up your findings if you get a chance :) If an official CSS-in-JS add-on is going to be a while in coming it would be useful to have a good idea of what direction the design is likely to go in so that there will be a good migration path from libraries like react-style.

**Comment by SanderSpies** [comment]
@robertknight The changes I'm currently making for React Style are to align correctly with the ideas of @vjeux and the React team. I'll probably push these changes to master/npm during the weekend.

If you look at: https://github.com/reactjs/react-future/blob/master/04%20-%20Layout/04%20-%20Inline%20Styles.md - you'll see that we're fairly similar to this with the inline-styles branch.

**Comment by ronag** [comment]
It would be really nice if we could have a easy way to use the same syntax referencing regular css files. i.e. when you want to use a css framework like bootstrap.

**Comment by SanderSpies** [comment]
Not sure if I understand correctly - do you want to create styles from a CSS file?

**Comment by ronag** [comment]
Yes, it would be nice to "import" existing CSS files into the same syntax, as to not having to mix and match between `style` and `className`.

**Comment by SanderSpies** [comment]
You should be able to do: `['someclass', ReactStyle({backgroundColor:'green'}), someBuildStyle]` within the inline styles branch. Does that mostly do the trick?
